/**
 * Every operation in the Forem API v1 spec, mapped to the SDK method that calls it.
 *
 * This file is the definition of "complete coverage". `coverage.test.ts` checks two
 * things against it: that it still matches the vendored OpenAPI spec, and that every
 * method really sends the request it claims to send.
 */

import type { DevToClient } from "../src/index.js";

export interface ApiOperation {
  method: string;
  /** The path exactly as it appears in the OpenAPI spec. */
  pattern: string;
  /** The path this SDK method is expected to request. */
  path: string;
  /** A call that exercises the method. */
  call: (devto: DevToClient) => Promise<unknown>;
}

const LIKE = { category: "like", reactableId: 1, reactableType: "Article" } as const;
const NEWSLETTER = { notification_setting: { email_newsletter: true } };

export const API_COVERAGE: ApiOperation[] = [
  {
    method: "DELETE",
    pattern: "/api/admin/concepts/{id}",
    path: "/api/admin/concepts/1",
    call: (devto) => devto.concepts.adminDelete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/admin/request_redirects/{id}",
    path: "/api/admin/request_redirects/1",
    call: (devto) => devto.requestRedirects.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/admin/users/{user_id}/identities/{id}",
    path: "/api/admin/users/1/identities/2",
    call: (devto) => devto.users.adminDeleteIdentity(1, 2),
  },
  {
    method: "DELETE",
    pattern: "/api/badge_achievements/{id}",
    path: "/api/badge_achievements/1",
    call: (devto) => devto.badgeAchievements.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/badges/{id}",
    path: "/api/badges/1",
    call: (devto) => devto.badges.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/organizations/{id}",
    path: "/api/organizations/1",
    call: (devto) => devto.organizations.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/pages/{id}",
    path: "/api/pages/1",
    call: (devto) => devto.pages.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/segments/{id}",
    path: "/api/segments/1",
    call: (devto) => devto.segments.delete(1),
  },
  {
    method: "DELETE",
    pattern: "/api/users/{id}/limited",
    path: "/api/users/1/limited",
    call: (devto) => devto.users.unlimit(1),
  },
  {
    method: "DELETE",
    pattern: "/api/users/{id}/spam",
    path: "/api/users/1/spam",
    call: (devto) => devto.users.unspam(1),
  },
  {
    method: "DELETE",
    pattern: "/api/users/{id}/trusted",
    path: "/api/users/1/trusted",
    call: (devto) => devto.users.untrust(1),
  },
  {
    method: "GET",
    pattern: "/api/admin/concepts",
    path: "/api/admin/concepts",
    call: (devto) => devto.concepts.adminList(),
  },
  {
    method: "GET",
    pattern: "/api/admin/concepts/{id}",
    path: "/api/admin/concepts/1",
    call: (devto) => devto.concepts.adminGet(1),
  },
  {
    method: "GET",
    pattern: "/api/admin/request_redirects",
    path: "/api/admin/request_redirects",
    call: (devto) => devto.requestRedirects.list(),
  },
  {
    method: "GET",
    pattern: "/api/admin/request_redirects/{id}",
    path: "/api/admin/request_redirects/1",
    call: (devto) => devto.requestRedirects.get(1),
  },
  {
    method: "GET",
    pattern: "/api/admin/users",
    path: "/api/admin/users",
    call: (devto) => devto.users.adminList(),
  },
  {
    method: "GET",
    pattern: "/api/admin/users/{id}",
    path: "/api/admin/users/1",
    call: (devto) => devto.users.adminGet(1),
  },
  {
    method: "GET",
    pattern: "/api/admin/users/{user_id}/identities",
    path: "/api/admin/users/1/identities",
    call: (devto) => devto.users.adminListIdentities(1),
  },
  {
    method: "GET",
    pattern: "/api/admin/users/{user_id}/notes",
    path: "/api/admin/users/1/notes",
    call: (devto) => devto.users.adminListNotes(1),
  },
  {
    method: "GET",
    pattern: "/api/agent_sessions",
    path: "/api/agent_sessions",
    call: (devto) => devto.agentSessions.list(),
  },
  {
    method: "GET",
    pattern: "/api/agent_sessions/{id}",
    path: "/api/agent_sessions/1",
    call: (devto) => devto.agentSessions.get(1),
  },
  {
    method: "GET",
    pattern: "/api/analytics/dashboard",
    path: "/api/analytics/dashboard",
    call: (devto) => devto.analytics.dashboard(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/follower_engagement",
    path: "/api/analytics/follower_engagement",
    call: (devto) => devto.analytics.followerEngagement(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/heatmap",
    path: "/api/analytics/heatmap",
    call: (devto) => devto.analytics.heatmap(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/historical",
    path: "/api/analytics/historical",
    call: (devto) => devto.analytics.historical({ start: "2026-01-01" }),
  },
  {
    method: "GET",
    pattern: "/api/analytics/past_day",
    path: "/api/analytics/past_day",
    call: (devto) => devto.analytics.pastDay(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/referrers",
    path: "/api/analytics/referrers",
    call: (devto) => devto.analytics.referrers(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/top_contributors",
    path: "/api/analytics/top_contributors",
    call: (devto) => devto.analytics.topContributors(),
  },
  {
    method: "GET",
    pattern: "/api/analytics/totals",
    path: "/api/analytics/totals",
    call: (devto) => devto.analytics.totals(),
  },
  {
    method: "GET",
    pattern: "/api/articles",
    path: "/api/articles",
    call: (devto) => devto.articles.list(),
  },
  {
    method: "GET",
    pattern: "/api/articles/latest",
    path: "/api/articles/latest",
    call: (devto) => devto.articles.latest(),
  },
  {
    method: "GET",
    pattern: "/api/articles/me",
    path: "/api/articles/me",
    call: (devto) => devto.articles.mine(),
  },
  {
    method: "GET",
    pattern: "/api/articles/me/all",
    path: "/api/articles/me/all",
    call: (devto) => devto.articles.mineAll(),
  },
  {
    method: "GET",
    pattern: "/api/articles/me/published",
    path: "/api/articles/me/published",
    call: (devto) => devto.articles.minePublished(),
  },
  {
    method: "GET",
    pattern: "/api/articles/me/unpublished",
    path: "/api/articles/me/unpublished",
    call: (devto) => devto.articles.mineUnpublished(),
  },
  {
    method: "GET",
    pattern: "/api/articles/search",
    path: "/api/articles/search",
    call: (devto) => devto.articles.search({ q: "x" }),
  },
  {
    method: "GET",
    pattern: "/api/articles/{id}",
    path: "/api/articles/1",
    call: (devto) => devto.articles.get(1),
  },
  {
    method: "GET",
    pattern: "/api/articles/{username}/{slug}",
    path: "/api/articles/user/slug",
    call: (devto) => devto.articles.getByPath("user", "slug"),
  },
  {
    method: "GET",
    pattern: "/api/badge_achievements",
    path: "/api/badge_achievements",
    call: (devto) => devto.badgeAchievements.list(),
  },
  {
    method: "GET",
    pattern: "/api/badge_achievements/{id}",
    path: "/api/badge_achievements/1",
    call: (devto) => devto.badgeAchievements.get(1),
  },
  {
    method: "GET",
    pattern: "/api/badges",
    path: "/api/badges",
    call: (devto) => devto.badges.list(),
  },
  {
    method: "GET",
    pattern: "/api/badges/{id}",
    path: "/api/badges/1",
    call: (devto) => devto.badges.get(1),
  },
  {
    method: "GET",
    pattern: "/api/billboards",
    path: "/api/billboards",
    call: (devto) => devto.billboards.list(),
  },
  {
    method: "GET",
    pattern: "/api/billboards/{id}",
    path: "/api/billboards/1",
    call: (devto) => devto.billboards.get(1),
  },
  {
    method: "GET",
    pattern: "/api/comments",
    path: "/api/comments",
    call: (devto) => devto.comments.list({ aId: 1 }),
  },
  {
    method: "GET",
    pattern: "/api/comments/{id}",
    path: "/api/comments/abc",
    call: (devto) => devto.comments.get("abc"),
  },
  {
    method: "GET",
    pattern: "/api/concepts",
    path: "/api/concepts",
    call: (devto) => devto.concepts.list(),
  },
  {
    method: "GET",
    pattern: "/api/concepts/{id}",
    path: "/api/concepts/1",
    call: (devto) => devto.concepts.get(1),
  },
  {
    method: "GET",
    pattern: "/api/concepts/{id}/articles",
    path: "/api/concepts/1/articles",
    call: (devto) => devto.concepts.articles(1),
  },
  {
    method: "GET",
    pattern: "/api/followers/users",
    path: "/api/followers/users",
    call: (devto) => devto.followers.list(),
  },
  {
    method: "GET",
    pattern: "/api/follows/tags",
    path: "/api/follows/tags",
    call: (devto) => devto.follows.tags(),
  },
  {
    method: "GET",
    pattern: "/api/health_checks/app",
    path: "/api/health_checks/app",
    call: (devto) => devto.healthChecks.app(),
  },
  {
    method: "GET",
    pattern: "/api/health_checks/cache",
    path: "/api/health_checks/cache",
    call: (devto) => devto.healthChecks.cache(),
  },
  {
    method: "GET",
    pattern: "/api/health_checks/database",
    path: "/api/health_checks/database",
    call: (devto) => devto.healthChecks.database(),
  },
  {
    method: "GET",
    pattern: "/api/instance",
    path: "/api/instance",
    call: (devto) => devto.instance.get(),
  },
  {
    method: "GET",
    pattern: "/api/organizations",
    path: "/api/organizations",
    call: (devto) => devto.organizations.list(),
  },
  {
    method: "GET",
    pattern: "/api/organizations/{id}",
    path: "/api/organizations/1",
    call: (devto) => devto.organizations.getById(1),
  },
  {
    method: "GET",
    pattern: "/api/organizations/{organization_id_or_username}/articles",
    path: "/api/organizations/org/articles",
    call: (devto) => devto.organizations.articles("org"),
  },
  {
    method: "GET",
    pattern: "/api/organizations/{organization_id_or_username}/users",
    path: "/api/organizations/org/users",
    call: (devto) => devto.organizations.users("org"),
  },
  {
    method: "GET",
    pattern: "/api/organizations/{username}",
    path: "/api/organizations/org",
    call: (devto) => devto.organizations.get("org"),
  },
  {
    method: "GET",
    pattern: "/api/pages",
    path: "/api/pages",
    call: (devto) => devto.pages.list(),
  },
  {
    method: "GET",
    pattern: "/api/pages/{id}",
    path: "/api/pages/1",
    call: (devto) => devto.pages.get(1),
  },
  {
    method: "GET",
    pattern: "/api/podcast_episodes",
    path: "/api/podcast_episodes",
    call: (devto) => devto.podcastEpisodes.list(),
  },
  {
    method: "GET",
    pattern: "/api/profile_images/{username}",
    path: "/api/profile_images/user",
    call: (devto) => devto.profileImages.get("user"),
  },
  {
    method: "GET",
    pattern: "/api/readinglist",
    path: "/api/readinglist",
    call: (devto) => devto.readingList.list(),
  },
  {
    method: "GET",
    pattern: "/api/recommended_articles_lists",
    path: "/api/recommended_articles_lists",
    call: (devto) => devto.recommendedLists.list(),
  },
  {
    method: "GET",
    pattern: "/api/recommended_articles_lists/{id}",
    path: "/api/recommended_articles_lists/1",
    call: (devto) => devto.recommendedLists.get(1),
  },
  {
    method: "GET",
    pattern: "/api/segments",
    path: "/api/segments",
    call: (devto) => devto.segments.list(),
  },
  {
    method: "GET",
    pattern: "/api/segments/{id}",
    path: "/api/segments/1",
    call: (devto) => devto.segments.get(1),
  },
  {
    method: "GET",
    pattern: "/api/segments/{id}/users",
    path: "/api/segments/1/users",
    call: (devto) => devto.segments.users(1),
  },
  {
    method: "GET",
    pattern: "/api/subforems",
    path: "/api/subforems",
    call: (devto) => devto.subforems.list(),
  },
  {
    method: "GET",
    pattern: "/api/surveys",
    path: "/api/surveys",
    call: (devto) => devto.surveys.list(),
  },
  {
    method: "GET",
    pattern: "/api/surveys/{id_or_slug}",
    path: "/api/surveys/item",
    call: (devto) => devto.surveys.get("item"),
  },
  {
    method: "GET",
    pattern: "/api/surveys/{id_or_slug}/poll_text_responses",
    path: "/api/surveys/item/poll_text_responses",
    call: (devto) => devto.surveys.pollTextResponses("item"),
  },
  {
    method: "GET",
    pattern: "/api/surveys/{id_or_slug}/poll_votes",
    path: "/api/surveys/item/poll_votes",
    call: (devto) => devto.surveys.pollVotes("item"),
  },
  {
    method: "GET",
    pattern: "/api/tags",
    path: "/api/tags",
    call: (devto) => devto.tags.list(),
  },
  {
    method: "GET",
    pattern: "/api/trends",
    path: "/api/trends",
    call: (devto) => devto.trends.list(),
  },
  {
    method: "GET",
    pattern: "/api/trends/{id_or_slug}",
    path: "/api/trends/trend",
    call: (devto) => devto.trends.get("trend"),
  },
  {
    method: "GET",
    pattern: "/api/trends/{trend_id_or_slug}/articles",
    path: "/api/trends/trend/articles",
    call: (devto) => devto.trends.articles("trend"),
  },
  {
    method: "GET",
    pattern: "/api/users/me",
    path: "/api/users/me",
    call: (devto) => devto.users.me(),
  },
  {
    method: "GET",
    pattern: "/api/users/search",
    path: "/api/users/search",
    call: (devto) => devto.users.search("a@b.co"),
  },
  {
    method: "GET",
    pattern: "/api/users/{id}",
    path: "/api/users/1",
    call: (devto) => devto.users.get(1),
  },
  {
    method: "GET",
    pattern: "/api/videos",
    path: "/api/videos",
    call: (devto) => devto.videos.list(),
  },
  {
    method: "PATCH",
    pattern: "/api/admin/concepts/{id}",
    path: "/api/admin/concepts/1",
    call: (devto) => devto.concepts.adminUpdate(1, { name: "n" }),
  },
  {
    method: "PATCH",
    pattern: "/api/admin/request_redirects/{id}",
    path: "/api/admin/request_redirects/1",
    call: (devto) => devto.requestRedirects.update(1, { original_url: "a" }),
  },
  {
    method: "PATCH",
    pattern: "/api/admin/users/{id}",
    path: "/api/admin/users/1",
    call: (devto) => devto.users.adminUpdate(1, { name: "n" }),
  },
  {
    method: "PATCH",
    pattern: "/api/badges/{id}",
    path: "/api/badges/1",
    call: (devto) => devto.badges.update(1, { title: "t" }),
  },
  {
    method: "PATCH",
    pattern: "/api/concepts/{id}",
    path: "/api/concepts/1",
    call: (devto) => devto.concepts.update(1, { score: 1 }),
  },
  {
    method: "PATCH",
    pattern: "/api/feedback_messages/{id}",
    path: "/api/feedback_messages/1",
    call: (devto) => devto.feedbackMessages.update(1, "Resolved"),
  },
  {
    method: "PATCH",
    pattern: "/api/recommended_articles_lists/{id}",
    path: "/api/recommended_articles_lists/1",
    call: (devto) => devto.recommendedLists.update(1, { name: "n" }),
  },
  {
    method: "POST",
    pattern: "/api/admin/concepts",
    path: "/api/admin/concepts",
    call: (devto) => devto.concepts.adminCreate({ name: "n" }),
  },
  {
    method: "POST",
    pattern: "/api/admin/concepts/{id}/trigger_lookback",
    path: "/api/admin/concepts/1/trigger_lookback",
    call: (devto) => devto.concepts.adminTriggerLookback(1, 7),
  },
  {
    method: "POST",
    pattern: "/api/admin/request_redirects",
    path: "/api/admin/request_redirects",
    call: (devto) => devto.requestRedirects.create({ original_url: "a" }),
  },
  {
    method: "POST",
    pattern: "/api/admin/users",
    path: "/api/admin/users",
    call: (devto) => devto.users.adminCreate({ email: "a@b.co" }),
  },
  {
    method: "POST",
    pattern: "/api/admin/users/identities/bulk",
    path: "/api/admin/users/identities/bulk",
    call: (devto) => devto.users.adminBulkIdentities({ provider: "p", identities: [] }),
  },
  {
    method: "POST",
    pattern: "/api/admin/users/{id}/merge",
    path: "/api/admin/users/1/merge",
    call: (devto) => devto.users.adminMerge(1, 2),
  },
  {
    method: "POST",
    pattern: "/api/admin/users/{user_id}/identities",
    path: "/api/admin/users/1/identities",
    call: (devto) => devto.users.adminCreateIdentity(1, { provider: "p", uid: "u" }),
  },
  {
    method: "POST",
    pattern: "/api/admin/users/{user_id}/notes",
    path: "/api/admin/users/1/notes",
    call: (devto) => devto.users.adminCreateNote(1, { content: "c" }),
  },
  {
    method: "POST",
    pattern: "/api/agent_sessions",
    path: "/api/agent_sessions",
    call: (devto) => devto.agentSessions.create({ title: "t" }),
  },
  {
    method: "POST",
    pattern: "/api/articles",
    path: "/api/articles",
    call: (devto) => devto.articles.create({ title: "t" }),
  },
  {
    method: "POST",
    pattern: "/api/badge_achievements",
    path: "/api/badge_achievements",
    call: (devto) => devto.badgeAchievements.create({ user_id: 1, badge_id: 2 }),
  },
  {
    method: "POST",
    pattern: "/api/badges",
    path: "/api/badges",
    call: (devto) => devto.badges.create({ title: "t" }),
  },
  {
    method: "POST",
    pattern: "/api/billboards",
    path: "/api/billboards",
    call: (devto) => devto.billboards.create({}),
  },
  {
    method: "POST",
    pattern: "/api/follows",
    path: "/api/follows",
    call: (devto) => devto.follows.create({ userIds: [1] }),
  },
  {
    method: "POST",
    pattern: "/api/organizations",
    path: "/api/organizations",
    call: (devto) => devto.organizations.create({ name: "n" }),
  },
  {
    method: "POST",
    pattern: "/api/pages",
    path: "/api/pages",
    call: (devto) => devto.pages.create({ title: "t" }),
  },
  {
    method: "POST",
    pattern: "/api/reactions",
    path: "/api/reactions",
    call: (devto) => devto.reactions.create(LIKE),
  },
  {
    method: "POST",
    pattern: "/api/reactions/toggle",
    path: "/api/reactions/toggle",
    call: (devto) => devto.reactions.toggle(LIKE),
  },
  {
    method: "POST",
    pattern: "/api/recommended_articles_lists",
    path: "/api/recommended_articles_lists",
    call: (devto) => devto.recommendedLists.create({ placement_area: "x", user_id: 1 }),
  },
  {
    method: "POST",
    pattern: "/api/segments",
    path: "/api/segments",
    call: (devto) => devto.segments.create(),
  },
  {
    method: "PUT",
    pattern: "/api/admin/users/{id}/email",
    path: "/api/admin/users/1/email",
    call: (devto) => devto.users.adminUpdateEmail(1, "a@b.co"),
  },
  {
    method: "PUT",
    pattern: "/api/admin/users/{id}/notification_settings",
    path: "/api/admin/users/1/notification_settings",
    call: (devto) => devto.users.adminUpdateNotificationSettings(1, NEWSLETTER),
  },
  {
    method: "PUT",
    pattern: "/api/admin/users/{id}/status",
    path: "/api/admin/users/1/status",
    call: (devto) => devto.users.adminUpdateStatus(1, { status: "s" }),
  },
  {
    method: "PUT",
    pattern: "/api/articles/{id}",
    path: "/api/articles/1",
    call: (devto) => devto.articles.update(1, { title: "t" }),
  },
  {
    method: "PUT",
    pattern: "/api/articles/{id}/unpublish",
    path: "/api/articles/1/unpublish",
    call: (devto) => devto.articles.unpublish(1),
  },
  {
    method: "PUT",
    pattern: "/api/billboards/{id}",
    path: "/api/billboards/1",
    call: (devto) => devto.billboards.update(1, {}),
  },
  {
    method: "PUT",
    pattern: "/api/billboards/{id}/unpublish",
    path: "/api/billboards/1/unpublish",
    call: (devto) => devto.billboards.unpublish(1),
  },
  {
    method: "PUT",
    pattern: "/api/organizations/{id}",
    path: "/api/organizations/1",
    call: (devto) => devto.organizations.update(1, { name: "n" }),
  },
  {
    method: "PUT",
    pattern: "/api/pages/{id}",
    path: "/api/pages/1",
    call: (devto) => devto.pages.update(1, { title: "t" }),
  },
  {
    method: "PUT",
    pattern: "/api/segments/{id}/add_users",
    path: "/api/segments/1/add_users",
    call: (devto) => devto.segments.addUsers(1, [2]),
  },
  {
    method: "PUT",
    pattern: "/api/segments/{id}/remove_users",
    path: "/api/segments/1/remove_users",
    call: (devto) => devto.segments.removeUsers(1, [2]),
  },
  {
    method: "PUT",
    pattern: "/api/users/{id}/limited",
    path: "/api/users/1/limited",
    call: (devto) => devto.users.limit(1),
  },
  {
    method: "PUT",
    pattern: "/api/users/{id}/spam",
    path: "/api/users/1/spam",
    call: (devto) => devto.users.spam(1),
  },
  {
    method: "PUT",
    pattern: "/api/users/{id}/suspend",
    path: "/api/users/1/suspend",
    call: (devto) => devto.users.suspend(1),
  },
  {
    method: "PUT",
    pattern: "/api/users/{id}/trusted",
    path: "/api/users/1/trusted",
    call: (devto) => devto.users.trust(1),
  },
  {
    method: "PUT",
    pattern: "/api/users/{id}/unpublish",
    path: "/api/users/1/unpublish",
    call: (devto) => devto.users.unpublish(1),
  },
];
